### ISSUE TITLE
Null Reference Exception  at Akka.Persistence.Journal.AsyncWriteJournal Constructor

### ISSUE THREAD

**Issue by jalchr** [akkadotnet/Akka.Persistence.SqlServer#106]
Akka v1.3.11

Everything was working fine for months. I have a scheduled restart of the windows service hosting this application.
Today, I got this error.

```
2019-04-15 04:09:18,798 [1] INFO  Archive.Api.Startup - ActorSystem Started !
2019-04-15 04:09:18,798 [1] INFO  Archive.Api.Startup - ASP.NET application started !
2019-04-15 04:09:18,829 [11] INFO  Archive.Shared.Export.VideoMaster - [PreStart] VideoMaster
2019-04-15 04:09:18,829 [27] INFO  Archive.Shared.Export.ApiMaster - [PreStart] ApiMaster
2019-04-15 04:09:18,954 [30] ERROR Akka.Actor.OneForOneStrategy - Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.SqlServerJournal with 1 args: (  class : "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
  plugin-dispatcher : akka.actor.default-dispatcher
  connection-string : "Server=.;Database=AkkaPersistenceArchiveDb;User ID=sa;Password=xxxxx;Connection Timeout=30;MultipleActiveResultSets=True; Pooling=True; Min Pool Size=2; Connect Timeout=250;"
  connection-timeout : 30s
  schema-name : dbo
  table-name : EventJournal
  auto-initialize : on
  timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
  metadata-table-name : Metadata
)
[akka://ArchiveSystem/system/akka.persistence.journal.sql-server#15922092]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.SqlServerJournal with 1 args: (  class : "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
  plugin-dispatcher : akka.actor.default-dispatcher
  connection-string : "Server=.;Database=AkkaPersistenceArchiveDb;User ID=sa;Password=xxxxx;Connection Timeout=30;MultipleActiveResultSets=True; Pooling=True; Min Pool Size=2; Connect Timeout=250;"
  connection-timeout : 30s
  schema-name : dbo
  table-name : EventJournal
  auto-initialize : on
  timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
  metadata-table-name : Metadata
) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Persistence.Journal.AsyncWriteJournal..ctor()
   at Akka.Persistence.Sql.Common.Journal.SqlJournal..ctor(Config journalConfig)
   at Akka.Persistence.SqlServer.Journal.SqlServerJournal..ctor(Config journalConfig)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
2019-04-15 04:09:19,063 [30] WARN  Archive.Shared.Cluster.ClusterStatus - ClusterLeader is null
2019-04-15 04:09:19,720 [11] INFO  Akka.Event.DummyClassForStringSources - Cluster Node [akka.tcp://ArchiveSystem@140.125.4.3:16666] - Welcome from [akka.tcp://ArchiveSystem@140.125.4.6:4053]
...
```

**Comment by Aaronontheweb** [comment]
Believe this was fixed by https://github.com/akkadotnet/akka.net/pull/3770 - we'll be updating to use 1.3.13 ASAP.

**Comment by jalchr** [comment]
Thanks... I'll update to v1.3.13 and inform you with my findings

**Comment by Aaronontheweb** [comment]
@jalchr any updates on this?

**Comment by jalchr** [comment]
I'm monitoring this ... haven't faced in it yet after upgrading to v1.3.13. 
Will keep you posted
