### ISSUE TITLE
Error during snapshot store initialization

### ISSUE THREAD

**Issue by mrn-aglic** [akkadotnet/Akka.Persistence.SqlServer#111]
Trying to make an Akka.Persistence example with sql server and autoinit of tables. However, the snapshot table fails to create.

I'm using Akka.NET 1.3.13.

Here is my HOCON:
```
akka {
          persistence {
            journal {
              plugin = "akka.persistence.journal.sql-server"
              sql-server {
                class = "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
                schema-name = dbo
                auto-initialize = on
                connection-string = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\\\\Mac\\Dropbox\\Nastava\\2018-2019\\RS_18-19\\Vj07\\PersistentActorExample\\PersistentActorExample\\App_Data\\Persistence.mdf;Integrated Security=True"
              }
            } 
            snapshot-store {
              plugin = "akka.persistence.snapshot-store.sql-server"
              sql-server {
                class = "Akka.Persistence.SqlServer.Snapshot.SqlServerSnapshotStore, Akka.Persistence.SqlServer"
                schema-name = dbo
                auto-initialize = on
                connection-string = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\\\\Mac\\Dropbox\\Nastava\\2018-2019\\RS_18-19\\Vj07\\PersistentActorExample\\PersistentActorExample\\App_Data\\Persistence.mdf;Integrated Security=True"
              }
            }
          }   
        }
```

I'm working on a OSX with parallels running windows 10. 

Here is the error that occurs:
```
[ERROR][5/5/2019 9:56:15 PM][Thread 0009][[akka://persistence-example/system/akka.persistence.snapshot-store.sql-server#670725692]] Error during snapshot store initialization
Cause: System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '('.
Incorrect syntax near '('.
Incorrect syntax near '('.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Snapshot.AbstractQueryExecutor.<CreateTableAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.<Initialize>d__17.MoveNext()
ClientConnectionId:69ba6e78-21b1-4cda-999b-94b7b0f703a5
Error Number:102,State:1,Class:15
```

The tables EventJournal and Metadata are created.

**Comment by Horusiath** [comment]
Script executing snapshot table creation can be found [here](https://github.com/akkadotnet/Akka.Persistence.SqlServer/blob/dev/src/Akka.Persistence.SqlServer/Snapshot/SqlServerQueryExecutor.cs#L19). It's really strange, that you're running into this issue, as snapshot table is created during test runs.

**Comment by lesscodetxm** [comment]
I'm seeing the same error

**Comment by lesscodetxm** [comment]
Actually when I debug, it seems that `SnapshotTableName` is `null`. Is there supposed to be a default for that? Anyway, I added `table-name = Snapshots` to my config and it's working.

**Comment by mrn-aglic** [comment]
I took a quick look at the sql-server.conf file (I assume this is the configuration), and the table-name proprty is set
```
# SQL server table corresponding with persistent journal
table-name = SnapshotStore
```

I haven't tried your fix yet, but it is kind of strange that the error is happening...

**Comment by lesscodetxm** [comment]
Looks like the snapshot store is not using the fallback config: I think this should fix it: https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/112

**Comment by Aaronontheweb** [comment]
close via #112
