### ISSUE TITLE
Batching journal not working with Akka.Persistence v1.4.11

### ISSUE THREAD

**Issue by raskolnikoov** [akkadotnet/Akka.Persistence.SqlServer#177]
Hi,

Seems to be some errors when using the latest Akka.Persistence v1.4.11 with Akka.Persistence.SqlServer v.1.4.10 and SqlServer Batching journal.

Upon upstart this error is thrown. If I switch to standard SqlServer journal it works.

`[akka://OMP/system/akka.persistence.journal.sql-server#1258631903]: Akka.Actor.ActorInitializationException: Exception during creation
 ---> System.TypeLoadException: Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.BatchingSqlServerJournal with 1 args: (  class : "Akka.Persistence.SqlServer.Journal.BatchingSqlServerJournal, Akka.Persistence.SqlServer"
  max-concurrent-operations : 64
  max-batch-size : 100
  max-buffer-size : 1000000
  plugin-dispatcher : akka.actor.default-dispatcher
  connection-string : Server=localhost;Database=MyFancyDb;Trusted_Connection=True;MultipleActiveResultSets=True;
  connection-timeout : 60s
  schema-name : dbo
  table-name : MyFancy_Persistance_EventJournal
  auto-initialize : on
  timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
  metadata-table-name : MyFancy_Persistance_Metadata
  circuit-breaker : {
    call-timeout : 80s
  }
)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Akka.Pattern.CircuitBreaker Akka.Pattern.CircuitBreaker.Create(Int32, System.TimeSpan, System.TimeSpan)'.
   at Akka.Persistence.Sql.Common.Journal.BatchingSqlJournal`2..ctor(BatchingSqlJournalSetup setup)
   at Akka.Persistence.SqlServer.Journal.BatchingSqlServerJournal..ctor(BatchingSqlServerJournalSetup setup)
   at Akka.Persistence.SqlServer.Journal.BatchingSqlServerJournal..ctor(Config config)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass117_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)`

**Comment by ismaelhamed** [comment]
Latest Akka release introduced a breaking change in the Circuit Breaker, so this plug-in needs to be recompiled against **1.4.11**

**Comment by ismaelhamed** [comment]
Actually, no. I just upgraded our solution, and it seems to be working fine. Can you make sure all the `Akka.*.dll` are actually on **v1.4.11**?

**Comment by Aaronontheweb** [comment]
@ismaelhamed should we just push the v1.4.11 version of Akka.Persistence.Sql with the updated dependencies?

**Comment by raskolnikoov** [comment]
Please do push an update since I was not referencing Akka.Persistence v1.4.11 in my project but only Akka.Persistence.SqlServer and therefore we have this bug when other akka packages are v1.4.11.

**Comment by ismaelhamed** [comment]
@Aaronontheweb yes, like @raskolnikoov said it'd be better from a user experience perspective to release a **v1.4.11** for the SqlServer plugin. Otherwise, user must manually update all the Akka.Persistence.* libraries himself.

**Comment by raskolnikoov** [comment]
@ismaelhamed I tried to install Akka.Persistence also in my app but I still get the same issue as before. It was resolved when I also installed Akka.Persistence.Sql.Common to v.1.4.11.

**Comment by ismaelhamed** [comment]
@raskolnikoov That's what I meant before. Because we cannot always guarantee backward compatibility, IMO users must make sure all Akka core packages are always on the same version. In this case, it would've been more straightforward if the SqlServer plugin had pulled down the latest version for its dependencies.

**Comment by Aaronontheweb** [comment]
@ismaelhamed @raskolnikoov got it - I'll push an update to Akka.Persistence.SqlServer and some of the other Akka.Persistence plugins today then.
