### ISSUE TITLE
Strange error when SaveSnapshotFailure

### ISSUE THREAD

**Issue by Pudev** [akkadotnet/Akka.Persistence.SqlServer#27]
I'm getting strange error when my persistent actor failed to save snaphot:

> Error in saving snapshot SnapshotMetadata<pid: TaskManager, seqNr: 218, timestamp: 0001-01-01>
> Cause: System.NotSupportedException: There is no active ActorContext, this is most likely due to use of async operations from within this actor.

How can I avoid this kind of SaveSnapshotFailure?

**Comment by Horusiath** [comment]
@Pudev can you provide a full stack trace for that error?

**Comment by Pudev** [comment]
[Thread 0006][[akka://TaskManagementSystem/user/tenantRouter/taskManager-46cc27cd-0d98-417c-a450-151970cb1858]] Failed
to SaveSnapshot given metadata [SnapshotMetadata<pid: TaskManager, seqNr: 323, timestamp: 0001-01-01>] due to: [System.NotSupportedException: There is
 no active ActorContext, this is most likely due to use of async operations from within this actor.
   at Akka.Actor.ActorBase.get_Context()
   at Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.ToSnapshotEntry(SnapshotMetadata metadata, Object snapshot)
   at Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.<SaveAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Akka.Pattern.Closed.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Akka.Pattern.CircuitBreaker.<WithCircuitBreaker>d__33.MoveNext(): There is no active ActorContext, this is most likely due to use of async opera
tions from within this actor.]

**Comment by philhack** [comment]
@Pudev did you happen to find a solution / workaround to this SaveSnapshotFailure error?

**Comment by Pudev** [comment]
I didn't find a solution for this issue
