### ISSUE TITLE
Incorrect SQL syntax when saving snapshot

### ISSUE THREAD

**Issue by object** [akkadotnet/Akka.Persistence.SqlServer#46]
Here's the callstack:

Unhandled message from akka://Oddjob/system/akka.persistence.snapshot-store.sql-server : SaveSnapshotFailure<meta: SnapshotMetadata<pid: akamai-volume-usage:22, seqNr: 1053, timestamp: 0001.01.01>, cause: System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'WHERE'.
Incorrect syntax near the keyword 'SET'.
Incorrect syntax near '('.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Snapshot.AbstractQueryExecutor.<InsertAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Snapshot.SqlSnapshotStore.<SaveAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Pattern.HalfOpen.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Pattern.CircuitBreaker.<WithCircuitBreaker>d__33.MoveNext()
ClientConnectionId:5a1a9a0c-5099-4e42-942b-cd935519dbfa
Error Number:156,State:1,Class:15>

**Comment by object** [comment]
We have probably identified the cause of this error, however something is not completely clear. In the configuration file we had schema-name for the database, but not table-name. And the failing statement had an empty table name. However, this raises another question: why does it fail occasionally and not all the time? We checked the code, and there is no default values for event journal and snapshot store, so missing table-name setting should always cause the error? But it doesn't.

**Comment by object** [comment]
Closing this because it's caused by misconfiguration, not a bug.

**Comment by feitzi** [comment]
I think the current behavior is confusing. Because in the documentation [articel ](https://petabridge.com/blog/intro-to-persistent-actors/)to akka.net persistence by Petabridge is no table-name configuration.

For all other people with the same problem, this is the minimal default configuration for a sqlServer snapshot store:
```
snapshot-store {
	plugin = "akka.persistence.snapshot-store.sql-server"
			sql-server {
				class = "Akka.Persistence.SqlServer.Snapshot.SqlServerSnapshotStore, Akka.Persistence.SqlServer"
				schema-name = dbo
				auto-initialize = on
				table-name = SnapshotStore
		     	connection-string = "Server=127.0.0.1,1433;Database=akkaSampleDb;Integrated Security=False;User Id=sa;Password=1234Test123!;MultipleActiveResultSets=True"
		 }
}
```
