### ISSUE TITLE
Current Akka.Persistence.SqlServer version incompatible with 1.1.2.x

### ISSUE THREAD

**Issue by dweggemans** [akkadotnet/Akka.Persistence.SqlServer#48]
In follow up on the ordering issue on SQL server: https://github.com/akkadotnet/akka.net/pull/2272

Please release a new nightly of package Akka.Persistence.SqlServer so it handles the new ordering column configuration. We're experiencing a missing method exception with the current 1.1.1.158-beta

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Void Akka.Persistence.Sql.Common.Journal.QueryConfiguration..ctor(System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.TimeSpan)'.
   at Akka.Persistence.SqlServer.Journal.SqlServerJournal..ctor(Config journalConfig)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass118_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)

Thanks :)

**Comment by cessationoftime** [comment]
:+1:

**Comment by andreyleskov** [comment]
👍
pls update packages, I've spent whole day trying to find wroking combination of packages with no success 8(

**Comment by Danthar** [comment]
https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/53

**Comment by TheeJamesLee** [comment]
Hi,
I can see the commits on master that put Akka.Persistence.SqlServer to 1.1.2, but I seem to only see up till 1.1.1.158-beta (4th August) on the nightly build nuget feed.  Did the publish not run?
Thanks,
