### ISSUE TITLE
Error when trying to persist actor

### ISSUE THREAD

**Issue by rambo406** [akkadotnet/Akka.Persistence.SqlServer#7]
```New transaction is not allowed because there are other threads running in the session.```

```
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at Akka.Persistence.Sql.Common.Journal.JournalDbEngine.<InsertInTransactionAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Journal.JournalDbEngine.<WriteMessagesAsync>d__6.MoveNext()
```

**Comment by Horusiath** [comment]
Related to akkadotnet/akka.net#1306

**Comment by rambo406** [comment]
@Horusiath First of all, thanks for the reply. Is there a quick fix on it? I see there are quite some changes in this commit https://github.com/Horusiath/akka.net/commit/18a5b981c2935b7dcc7ebef474150eaea01f6a1c

After get latest from your branch **query messaging mechanism for SQL-based journals**, **SqlJournalEngine** in Akka.Persistence.SqlServer need to re-implement too right?

**Comment by Horusiath** [comment]
@rambo406 yes, SqlServer side needs some changes too, including change of table schema. I've good ready commit for that, only waiting for changes from PR you mentioned to be accessible in Akka.NET nightly builds.
