### ISSUE TITLE
Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.SqlServerJournal

### ISSUE THREAD

**Issue by PeymanGhadiri** [akkadotnet/Akka.Persistence.SqlServer#75]
I updated the references to 1.3 and the app throws the following exception:
```
System.MissingMethodException: Method not found: 'Void Akka.Persistence.Sql.Common.Journal.QueryConfiguration..ctor(System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.TimeSpan)
```
akka packages:
```
  Akka                        1.3.0
  Akka.DI.AutoFac             1.0.8
  Akka.DI.Core                1.0.8
  Akka.Logger.NLog            1.2.0
  Akka.Persistence            1.3.0
  Akka.Persistence.Sql.Common 1.3.0
  Akka.Persistence.SqlServer  1.1.1.7-beta
  Akka.Remote                 1.3.0
```

full log:
```
2017-08-25 10:52:55.9321 [20] Info local-machine daemon Akka.Actor.Internal.ActorSystemImpl -   akka : {
    persistence : {
      journal : {
        plugin : akka.persistence.journal.sql-server
        sql-server : {
          class : "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
          plugin-dispatcher : akka.actor.default-dispatcher
          connection-string : "server=localhost; database=RapidBilling; user=sa; password=123456; Application Name=AdminBillingApi;"
          connection-timeout : 30s
          schema-name : dbo
          table-name : AkkaEventJournal
          auto-initialize : on
          timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
          metadata-table-name : AkkaMetadata
        }
      }
      snapshot-store : {
        plugin : akka.persistence.snapshot-store.sql-server
        sql-server : {
          class : "Akka.Persistence.SqlServer.Snapshot.SqlServerSnapshotStore, Akka.Persistence.SqlServer"
          plugin-dispatcher : akka.actor.default-dispatcher
          connection-string : "server=localhost; database=RapidBilling; user=sa; password=123456; Application Name=AdminBillingApi;"
          connection-timeout : 30s
          schema-name : dbo
          table-name : AkkaSnapshotStore
          auto-initialize : on
        }
      }
    }
    loggers : ["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]
    actor : {
      debug : {
        unhandled : on
        receive : on
        autoreceive : on
        lifecycle : on
        event-stream : on
      }
    }
    stdout-loglevel : Error
    loglevel : DEBUG
    log-config-on-start : on
  }
2017-08-25 10:52:55.9211 [7] Debug local-machine daemon Akka.Event.EventStream - subscribing [akka://BillingActorSystem/system/log1-NLogLogger#699980222] to channel Akka.Event.Error
2017-08-25 10:52:55.9211 [19] Warn local-machine daemon Akka.Actor.Internal.ActorSystemImpl - NewtonSoftJsonSerializer has been detected as a default serializer. It will be obsoleted in Akka.NET starting from version 1.5 in the favor of Hyperion (for more info visit: http://getakka.net/docs/Serialization#how-to-setup-hyperion-as-default-serializer ). If you want to suppress this message set HOCON `akka.suppress-json-serializer-warning` config flag to on.
2017-08-25 10:52:59.6202 [24] Error local-machine daemon Akka.Actor.OneForOneStrategy - Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.SqlServerJournal with 1 args: (  class : "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
  plugin-dispatcher : akka.actor.default-dispatcher
  connection-string : "server=localhost; database=RapidBilling; user=sa; password=123456; Application Name=AdminBillingApi;"
  connection-timeout : 30s
  schema-name : dbo
  table-name : AkkaEventJournal
  auto-initialize : on
  timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
  metadata-table-name : AkkaMetadata
)[akka://BillingActorSystem/system/akka.persistence.journal.sql-server#796296213]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.SqlServerJournal with 1 args: (  class : "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
  plugin-dispatcher : akka.actor.default-dispatcher
  connection-string : "server=localhost; database=RapidBilling; user=sa; password=123456; Application Name=AdminBillingApi;"
  connection-timeout : 30s
  schema-name : dbo
  table-name : AkkaEventJournal
  auto-initialize : on
  timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
  metadata-table-name : AkkaMetadata
) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Void Akka.Persistence.Sql.Common.Journal.QueryConfiguration..ctor(System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.TimeSpan)'.
   at Akka.Persistence.SqlServer.Journal.SqlServerJournal..ctor(Config journalConfig)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)[akka://BillingActorSystem/system/akka.persistence.journal.sql-server#796296213]: Akka.Actor.ActorInitializationException: Exception during creation ---> System.TypeLoadException: Error while creating actor instance of type Akka.Persistence.SqlServer.Journal.SqlServerJournal with 1 args: (  class : "Akka.Persistence.SqlServer.Journal.SqlServerJournal, Akka.Persistence.SqlServer"
  plugin-dispatcher : akka.actor.default-dispatcher
  connection-string : "server=localhost; database=RapidBilling; user=sa; password=123456; Application Name=AdminBillingApi;"
  connection-timeout : 30s
  schema-name : dbo
  table-name : AkkaEventJournal
  auto-initialize : on
  timestamp-provider : "Akka.Persistence.Sql.Common.Journal.DefaultTimestampProvider, Akka.Persistence.Sql.Common"
  metadata-table-name : AkkaMetadata
) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Void Akka.Persistence.Sql.Common.Journal.QueryConfiguration..ctor(System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.TimeSpan)'.
   at Akka.Persistence.SqlServer.Journal.SqlServerJournal..ctor(Config journalConfig)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.Create(Exception failure)
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.Create(Exception failure)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

The same source code works perfectly with the following packages:
```
  Akka                        1.2.0
  Akka.DI.AutoFac             1.0.8
  Akka.DI.Core                1.0.8
  Akka.Persistence            1.1.2.30-beta
  Akka.Persistence.Sql.Common 1.1.2.30-beta
  Akka.Persistence.SqlServer  1.1.1.7-beta
  Akka.Remote                 1.2.0
```

**Comment by Horusiath** [comment]
SQL Server plugin is not yet updated to changes made in v1.3. You can track the progress at #73
